const Nightmare = require('nightmare')
const expect = require('chai').expect

describe('Tweet Count', function() {

    this.timeout(50000);

    it('should search for the word "puppy" and "cat" near NDI then show the report', done => {
        Nightmare({show: true})
        .goto('http://localhost:3000/')
        .wait('input')
        .wait(1000 * 2)
        .type('input', 'puppy')
        .type('body', '\u0009')
        .type('body', '2018-03-25')
        .type('body', '\u0009')
        .type('body', '2018-03-30')
        .type('body', '\u0009')
        .type('body', '455 Massachusetts Ave NW')
        .type('body', '\u0009')
        .type('body', 'Washington')
        .type('body', '\u0009')
        .type('body', 'DC')
        .type('body', '\u0009')
        .type('body', 'US')
        .type('body', '\u0009')
        .type('body', '2')
        .type('body', '\u0009')
        .type('body', 'mi')
        .type('body', '\u0009')
        .type('body', 'en')
        .click('.btn-lg')
        .wait('.tweet-info')
        .wait(1000 * 2)
        .scrollTo(500, 0)
        .wait(1000 * 2)
        .insert('input', '')
        .wait(1000 * 2)
        .type('input', 'cat')
        .wait(1000 * 2)
        .scrollTo(500, 0)
        .wait(1000 * 2)
        .click('.btn-lg')
        .wait('.tweet-info')
        .wait(1000 * 2)
        .scrollTo(500, 0)
        .wait(1000 * 2)
        .scrollTo(0, 0)
        .wait(1000 * 2)
        .click('.nav-icon')
        .wait(1000 * 2)
        .evaluate(()=>{
            const elements = Array.from(document.querySelectorAll('.nav-link'))

            elements[1].click();
        })
        .wait('table')
        .scrollTo(500, 0)
        .wait(1000 * 5)
        .end()
        .then(result => { done() })
        .catch(done)
    })
})